baseurl = "https://kmchuck.netlify.com/"
title = "Chuck KahMeng"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "manni"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Chuck KahMeng"
    info = ""
    description = "The personal website and blog of KahMeng Chuck, software engineer and mathematician."
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon.iso"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/iamchuckss/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/kahmeng-chuck/"
    [[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    weight = 3
    url = "s2011297@gmail.com"

# Menu links
# [[menu.main]]
#     name = "Blog"
#     weight = 3
#     url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 1
    url = "/projects/"
[[menu.main]]
    name = "Resume"
    weight = 2
    url = "https://iamchuckss.github.io/chuck_resume.pdf"
